# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm
   # - run: npm install 
    - run: npm ci
   # - run: npm start
    - run: npm run build 
    - run: npm test

    
    - run: |
       npm pack
       ls 
       
    - uses: actions/upload-artifact@v3
      with:
         name: my-artifact
         path: my-app-0.1.0.tgz
    - name: Deploy on AWS EC2
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USERNAME: ${{ secrets.USERNAME  }}
         
      run: |
          echo "$PRIVATE_KEY" > PRIVATE_KEY.pem && chmod 600 PRIVATE_KEY.pem
          ls -lrth
          ssh -o StrictHostKeyChecking=no -i PRIVATE_KEY.pem ubuntu@13.235.254.198


         
    
